#!/bin/bash
#SBATCH -A sds_baek_energetic
#SBATCH -p gpu
#SBATCH -N 1
#SBATCH --gres=gpu
#SBATCH -t 8:00:00
#SBATCH --mem=32G
#SBATCH -o /sfs/gpfs/tardis/home/pdy2bw/Research/LatentPARC/latent_parc/PARCtorch/PARCtorch/3AE_LatentPARC/autoencoder/slurm_files/output_%j.log     # Save output file
#SBATCH -e /sfs/gpfs/tardis/home/pdy2bw/Research/LatentPARC/latent_parc/PARCtorch/PARCtorch/3AE_LatentPARC/autoencoder/slurm_files/error_%j.log       # Save error file
#SBATCH --mail-type=END                                # Send email when job finishes
#SBATCH --mail-user=pdy2bw@virginia.edu             # Your email address

module purge
module load apptainer pytorch/2.4.0

export PATH=~/.local/bin:$PATH
export LD_LIBRARY_PATH=$DIR/lib:$LD_LIBRARY_PATH
export PYTHON_PATH=$DIR/lib/python3.7/site-packages
export PATH=$PATH:/home/pdy2bw/.local/lib/python3.10/site-packages

which python
apptainer run --nv $CONTAINERDIR/pytorch-2.4.0.sif /sfs/gpfs/tardis/home/pdy2bw/Research/LatentPARC/latent_parc/PARCtorch/PARCtorch/3AE_LatentPARC/autoencoder/trainMLPAE.py